### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by hbc19** [alibaba/rax#1428]
I just followed the instruction in landing page of this repository and on **npm run start**

Error: no such file or directory
    at MemoryFileSystem.readFileSync (E:\code\myproj\node_modules\webpack-dev-middleware\node_modules\memory-fs\lib\MemoryFileSystem.js:107:10)
    at E:\code\myproj\node_modules\rax-plugin-ssr\src\ssr\setDev.js:67:37
    at Layer.handle [as handle_request] (E:\code\myproj\node_modules\express\lib\router\layer.js:95:5)
    at next (E:\code\myproj\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (E:\code\myproj\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (E:\code\myproj\node_modules\express\lib\router\layer.js:95:5)
    at E:\code\myproj\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (E:\code\myproj\node_modules\express\lib\router\index.js:335:12)
    at next (E:\code\myproj\node_modules\express\lib\router\index.js:275:10)
    at compression (E:\code\myproj\node_modules\compression\index.js:220:5)
    at Layer.handle [as handle_request] (E:\code\myproj\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (E:\code\myproj\node_modules\express\lib\router\index.js:317:13)
    at E:\code\myproj\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (E:\code\myproj\node_modules\express\lib\router\index.js:335:12)
    at next (E:\code\myproj\node_modules\express\lib\router\index.js:275:10)
    at next (E:\code\myproj\node_modules\express\lib\router\route.js:127:14)

**Comment by Orange-C** [comment]
Update your node_modules, there is a more friendly log about `npm run start`

Please wait until webpack finish compiling, you'll see 
![image](https://user-images.githubusercontent.com/8469262/67666815-881d7f80-f9a7-11e9-8a74-9f645f4ea721.png)
And then the dev pages will works fine

**Comment by wssgcg1213** [comment]
好像一直有这个问题, devserver 没启动完成的时候访问浏览器不会挂起请求, 会返回500和直接报错
