### ISSUE TITLE
[BUG] (node:59732) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by andycall** [alibaba/rax#1515]
**Describe the bug**
```bash
cd examples/helloworld
npm i rax@latest rax-scripts@latest driver-dom@latest
npm start
```
then rax-scripts crashs:

```
➜  hello-world git:(master) ✗ npm start

> hello-world@1.0.0 start /Users/andycall/work/rax/examples/hello-world
> rax-scripts start

(node:59732) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'map' of undefined
    at Context.getPlugins (/Users/andycall/work/rax/examples/hello-world/node_modules/scripts-core/src/core/Context.js:81:49)
    at new Context (/Users/andycall/work/rax/examples/hello-world/node_modules/scripts-core/src/core/Context.js:40:27)
    at module.exports (/Users/andycall/work/rax/examples/hello-world/node_modules/scripts-core/src/commands/dev.js:17:19)
    at Command.program.command.description.option.action (/Users/andycall/work/rax/examples/hello-world/node_modules/rax-scripts/bin/rax-scripts.js:17:5)
    at Command.listener (/Users/andycall/work/rax/examples/hello-world/node_modules/commander/index.js:291:8)
    at Command.emit (events.js:198:13)
    at Command.parseArgs (/Users/andycall/work/rax/examples/hello-world/node_modules/commander/index.js:672:12)
    at Command.parse (/Users/andycall/work/rax/examples/hello-world/node_modules/commander/index.js:459:21)
    at Object.<anonymous> (/Users/andycall/work/rax/examples/hello-world/node_modules/rax-scripts/bin/rax-scripts.js:50:9)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
(node:59732) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:59732) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

the package.json of helloworld
```
{
  "private": true,
  "name": "hello-world",
  "version": "1.0.0",
  "scripts": {
    "start": "rax-scripts start",
    "build": "rax-scripts build"
  },
  "dependencies": {
    "driver-dom": "^2.0.4",
    "rax": "^1.0.13"
  },
  "devDependencies": {
    "rax-scripts": "^2.0.4"
  }
}
```

**Comment by wssgcg1213** [comment]
![image](https://user-images.githubusercontent.com/3922719/69205086-e6dbb080-0b83-11ea-91b8-675aea062980.png)

应该是 build.json 不存在, 需要更友好的提示  @Orange-C

**Comment by Orange-C** [comment]
fixed in build-scripts
