### ISSUE TITLE
[BUG]windows下dev服务的路径问题

### ISSUE THREAD

**Issue by dlmys** [alibaba/rax#1714]
使用rax-cli初始化一个ssr web-app项目，windows下npm start启动dev服务时报错文件路径找不到，mac下无此问题，怀疑是读取文件时未使用运行 node 命令时所在的文件夹的绝对路径。错误日志如下：
`Error: no such file or directory
    at MemoryFileSystem.readFileSync (C:\web\demo\rax-ssr-demo\node_modules\memory-fs\lib\MemoryFileSystem.js:107:10)
    at C:\web\demo\rax-ssr-demo\node_modules\build-plugin-rax-ssr\src\ssr\setDev.js:82:40
    at Layer.handle [as handle_request] (C:\web\demo\rax-ssr-demo\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\web\demo\rax-ssr-demo\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\web\demo\rax-ssr-demo\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\web\demo\rax-ssr-demo\node_modules\express\lib\router\layer.js:95:5)
    at C:\web\demo\rax-ssr-demo\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (C:\web\demo\rax-ssr-demo\node_modules\express\lib\router\index.js:335:12)
    at next (C:\web\demo\rax-ssr-demo\node_modules\express\lib\router\index.js:275:10)
    at compression (C:\web\demo\rax-ssr-demo\node_modules\compression\index.js:220:5)
    at Layer.handle [as handle_request] (C:\web\demo\rax-ssr-demo\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\web\demo\rax-ssr-demo\node_modules\express\lib\router\index.js:317:13)
    at C:\web\demo\rax-ssr-demo\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\web\demo\rax-ssr-demo\node_modules\express\lib\router\index.js:335:12)
    at next (C:\web\demo\rax-ssr-demo\node_modules\express\lib\router\index.js:275:10)
    at next (C:\web\demo\rax-ssr-demo\node_modules\express\lib\router\route.js:127:14)`

不开启SSR访问 http://localhost:9999/ 同样会出现 ’Document Not Found‘，同样是文件路径问题。本来打算过完年给团队推广下Rax，结果第一步就卡死了。球球各位大佬帮忙处理下，毕竟windows开发者还是有那么多，感激不尽！！

**Comment by chenjun1011** [comment]
感谢您的反馈，非常抱歉我们在 Windows  上的兼容性问题给您造成了困扰

您可以先试下这个 beta 版本，build-plugin-rax-ssr@1.0.4-beta.0，如果验证没有问题，节后工作日我们会安排发布

另外，您截图的日志，是另外一个问题。目前我们的 dev 启动速度略慢，在还没有完全 ready的时候，访问了页面，就会报这个错误日志，这个问题也将在节后优化

**Comment by chenjun1011** [comment]
已修复
