### ISSUE TITLE
微信小程序Demo直接报错

### ISSUE THREAD

**Issue by SteveSuv** [alibaba/rax#1759]
**Describe the bug**
微信小程序Demo直接报错

**To Reproduce**
1. npm init rax app
2. npm start
3. 打开微信开发工具

**Expected behavior**
成功运行

**Screenshots**
![image](https://user-images.githubusercontent.com/35391006/75381310-7dea9e00-5913-11ea-95c7-13348dfca95c.png)

**报错信息:**
```
VM561:1 thirdScriptError
module ".\npm\jsx2mp-runtime" is not defined
Error: module ".\npm\jsx2mp-runtime" is not defined
    at require (http://127.0.0.1:13149/appservice/__dev__/WAService.js:2:1671596)
    at http://127.0.0.1:13149/appservice/__dev__/WAService.js:2:1671347
    at http://127.0.0.1:13149/appservice/app.js:3:22
    at require (http://127.0.0.1:13149/appservice/__dev__/WAService.js:2:1671737)
    at <anonymous>:1:1
    at HTMLScriptElement.scriptLoaded (http://127.0.0.1:13149/appservice/appservice?t=1582746329632:1269:21)
    at HTMLScriptElement.script.onload (http://127.0.0.1:13149/appservice/appservice?t=1582746329632:1281:20)
```

 (please complete the following information)
 - Device: PC
 - OS: win10
 - Browser:chrome
 - Rax Version :3.0.2

**Comment by SoloJiang** [comment]
#1757 已经修复，今天发布
