### ISSUE TITLE
[Question] sass问题

### ISSUE THREAD

**Issue by microlove1910** [alibaba/rax#1876]
根据官网引入sass
编译没问题，在请求时发生异常
```
Error: document is not defined
    at insertStyleElement (/opt/app/macao-ms/build/node/index.js:5989:15)
    at addStyle (/opt/app/macao-ms/build/node/index.js:6104:13)
    at modulesToDom (/opt/app/macao-ms/build/node/index.js:5977:18)
    at module.exports../node_modules/style-loader/dist/runtime/injectStylesIntoStyleTag.js.module.exports (/opt/app/macao-ms/build/node/index.js:6135:25)
    at Object../src/components/Materials/index.scss (/opt/app/macao-ms/build/node/index.js:6314:14)
    at __webpack_require__ (/opt/app/macao-ms/build/node/index.js:21:30)
    at Module../src/components/Materials/index.jsx (/opt/app/macao-ms/build/node/index.js:6245:69)
    at __webpack_require__ (/opt/app/macao-ms/build/node/index.js:21:30)
    at Module../src/pages/Home/index.jsx (/opt/app/macao-ms/build/node/index.js:6420:79)
    at __webpack_require__ (/opt/app/macao-ms/build/node/index.js:21:30)
    at Module../node_modules/build-plugin-rax-ssr/src/ssr/entryLoader.js?pagePath=%2F&scripts%5B0%5D=%2Fweb%2Findex.js&absoluteDocumentPath=%2Fopt%2Fapp%2Fmacao-ms%2Fsrc%2Fdocument%2Findex.jsx&absoluteShellPath=%2Fopt%2Fapp%2Fmacao-ms%2Fsrc%2Fshell%2Findex.jsx!./src/pages/Home/index.jsx (/opt/app/macao-ms/build/node/index.js:106:100)
    at __webpack_require__ (/opt/app/macao-ms/build/node/index.js:21:30)
    at Object.0 (/opt/app/macao-ms/build/node/index.js:6464:18)
    at __webpack_require__ (/opt/app/macao-ms/build/node/index.js:21:30)
    at /opt/app/macao-ms/build/node/index.js:85:18
    at Object.<anonymous> (/opt/app/macao-ms/build/node/index.js:88:10)
```
前端小白，求解！

**Comment by chenjun1011** [comment]
有没有配置 `MiniCssExtractPlugin` ?

**Comment by u404** [comment]
我也遇到了。抄了一下框架里自带的less和css的loader配置，算是解决了。以下是我修改的sassPlugin.js配置
`
const path = require("path")

// sassPlugin.js
module.exports = ({ onGetWebpackConfig }) => {
  onGetWebpackConfig((config) => {
    config.module
      .rule('scss')
      .test(/\.scss$/)
      .use('stylesheet-loader').loader('stylesheet-loader').options({ transformDescendantCombinator: true }).end()
      .use('postcss-loader').loader('postcss-loader').options({  
        path: path.resolve("./node_modules/build-plugin-rax-app/src/config"),
        ctx: {
          type: "inline"
        }
      }).end()
      .use('sass-loader').loader('sass-loader')

    console.log("sassPlugin.js", JSON.stringify(config.toConfig().module.rules, null, 2))
  });
}
`

**Comment by microlove1910** [comment]
战略性放弃了。

**Comment by chenjun1011** [comment]
> 战略性放弃了。

在这个 PR 中做了支持  https://github.com/raxjs/rax-scripts/pull/328
