### ISSUE TITLE
[Question] How request data in getInitialProps function under SSR mode?

### ISSUE THREAD

**Issue by AaronW-BE** [alibaba/rax#1936]
There is a post in official tutorial like below:
```
import fetch from 'isomorphic-unfetch'

function Page({ stars }) {
  return <div>Rax stars: {stars}</div>
}

Page.getInitialProps = async (ctx) => {
  const res = await fetch('https://api.github.com/repos/alibaba/rax')
  const json = await res.json()
  return { stars: json.stargazers_count };
}

export default Page
```
Did you guys test it under server rendering? I tested it, but it's doesn't work.
```
(node:39680) UnhandledPromiseRejectionWarning: TypeError: stackFrame.map is not a function      
    at print (D:\demo\rax-demo\node_modules\error-stack-tracey\src\index.js:33:35)
    at process.once (D:\demo\rax-demo\node_modules\build-plugin-rax-ssr\src\ssr\setDev.js:45:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:39680) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 8)
(node:39680) UnhandledPromiseRejectionWarning: TypeError: stackFrame.map is not a function
    at print (D:\demo\rax-demo\node_modules\error-stack-tracey\src\index.js:33:35)
    at process.once (D:\demo\rax-demo\node_modules\build-plugin-rax-ssr\src\ssr\setDev.js:45:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:39680) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 12)

```
Anybody knows tell me, thanks a lots.

**Comment by chenjun1011** [comment]
上面这个报错本质原因是  isomorphic-unfetch  在依赖时  node-fetch 时，没有处理好引用方式，可以使用  cross-fetch 这个包代替

另外，你的 package.json 中 build-plugin 相关插件的依赖是怎么样的？ 我看下 错误提示不够友好的问题

**Comment by AaronW-BE** [comment]
> 上面这个报错本质原因是 isomorphic-unfetch 在依赖时 node-fetch 时，没有处理好引用方式，可以使用 cross-fetch 这个包代替
> 
> 另外，你的 package.json 中 build-plugin 相关插件的依赖是怎么样的？ 我看下 错误提示不够友好的问题

cross-fetch一样没作用，build.json内容使用项目默认配置：
```
{
  "plugins": [
    [
      "build-plugin-rax-app",
      {
        "targets": ["web"],
        "type": "mpa"
      }
    ],
    "build-plugin-rax-ssr"
  ]
}

```

**Comment by AaronW-BE** [comment]
> 上面这个报错本质原因是 isomorphic-unfetch 在依赖时 node-fetch 时，没有处理好引用方式，可以使用 cross-fetch 这个包代替
> 
> 另外，你的 package.json 中 build-plugin 相关插件的依赖是怎么样的？ 我看下 错误提示不够友好的问题

刚才又试了一下，使用```cross-fetch/polyfill'```可以
