### ISSUE TITLE
[BUG] Failed to initialise

### ISSUE THREAD

**Issue by jcplus** [alibaba/rax#2023]
**Initialisation not work as expected**
```
+ rax-cli@3.2.6
updated 1 package in 2.881s
/usr/local/lib/node_modules/rax-cli/node_modules/fs-extra/lib/mkdirs/make-dir.js:85
      } catch {
              ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/rax-cli/node_modules/fs-extra/lib/mkdirs/index.js:3:44)
```

**To Reproduce**
Run `npm init rax PROJECT_NAME`

**Screenshots**
[Screenshot](https://i.ibb.co/vvDxcsY/Screen-Shot-2020-10-14-at-9-10-42-am.png)

 - Device: Mac
 - OS: OSX Catalina 10.15.6
 - Browser N/A
 - Rax CLI 3.2.6

**Comment by jcplus** [comment]
Temporary solution I found:

> rax-cli/node_modules/fs-extra/lib/mkdirs/make-dir.js (line 85 and 134)    
> rax-cli/node_modules/fs-extra/lib/empty/index.js (line 33)    
> rax-cli/node_modules/fs-extra/lib/remove/rimraf.js (line 293)    
> rax-cli/node_modules/fs-extra/lib/ensure/file.js (line 47)    
> /usr/local/lib/node_modules/rax-cli/node_modules/fs-extra/lib/ensure/symlink-type.js (line 22)    
Change `} catch {` to `} catch (error) {`

**Comment by SoloJiang** [comment]
Is fs-extra bug？

**Comment by SoloJiang** [comment]
I can not replay it

**Comment by jcplus** [comment]
Checked with fs-extra that is intented for nodejs 10+
