### ISSUE TITLE
现在新项目运行都报错了吗？不知道是否是自己本地环境问题[Question]

### ISSUE THREAD

**Issue by evinLiang** [alibaba/rax#2071]
node本地环境11.5.0
按官方demo走一次安装流程（无论是npx安装还是vscode ICEWORKS安装），运行`npm run start`就报错
```
Unhandled Rejection (Error): Loading CSS chunk vendor~d:pjlearn
axinitsrcpageshomeindex.chunk failed.
(http://localhost:3333/vendor~d:pjlearnaxinitsrcpageshomeindex.chunk.css)
(anonymous function)
unknown
HTMLLinkElement.onLinkComplete
./webpack/bootstrap:883
  880 | } else {
  881 | 	var errorType = event && (event.type === 'load' ? 'missing' : event.type);
  882 | 	var realHref = event && event.target && event.target.href || fullhref;
> 883 | 	var err = new Error("Loading CSS chunk " + chunkId + " failed.\n(" + realHref + ")");
      | ^  884 | 	err.code = "CSS_CHUNK_LOAD_FAILED";
  885 | 	err.type = errorType;
  886 | 	err.request = realHref;
View compiled
This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.  Click the 'X' or hit ESC to dismiss this message.
```
![微信截图_20210119182040](https://user-images.githubusercontent.com/32260962/105021074-16859180-5a83-11eb-8ef2-e0b94f98abb7.png)

啥情况啊

**Comment by SoloJiang** [comment]
可以提供可以复现的项目吗？我们好像没有类似的反馈

**Comment by evinLiang** [comment]
> 可以提供复现的项目吗？我们好像没有类似的反馈

怎么提交代码给你查看呢

**Comment by evinLiang** [comment]
> 可以提供复现的项目吗？我们好像没有类似的反馈

图片上传了，我的代码都是新建的，什么都没有改，就cnpm install后运行start就这样了，重新安装依赖也不行

**Comment by SoloJiang** [comment]
可以在 github 创建一个示例项目

**Comment by basilbai** [comment]
新建的项目，没有改动任何代码，安装依赖后运行报错
`
raxmini@0.1.0 start D:\demo\raxmini\raxmini
> rax-app start

rax-app 3.3.2
JSX+ enabled, documentation: https://rax.js.org/docs/guide/jsxplus
‼ ｢wds｣: transportMode is an experimental option, meaning its usage could potentially change without warning

* WeChat MiniProgram █████████████████████████ after chunk asset optimization (93%) SourceMapDevToolPlugin
 resolve sources

D:\demo\raxmini\raxmini\node_modules\rax-miniapp-runtime-webpack-plugin\src\utils\getSepProcessedPath.js:2
  return filePath.replace(/\\/g, '/'); // Avoid path error in Windows
                  ^

TypeError: Cannot read property 'replace' of undefined
    at module.exports (D:\demo\raxmini\raxmini\node_modules\rax-miniapp-runtime-webpack-plugin\src\utils\getSepProcessedPath.js:2:19)
    at generatePageJS (D:\demo\raxmini\raxmini\node_modules\rax-miniapp-runtime-webpack-plugin\src\generators\page.js:44:12)
    at D:\demo\raxmini\raxmini\node_modules\rax-miniapp-runtime-webpack-plugin\src\index.js:216:11
    at Array.forEach (<anonymous>)
    at D:\demo\raxmini\raxmini\node_modules\rax-miniapp-runtime-webpack-plugin\src\index.js:161:10
    at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\demo\raxmini\raxmini\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:27:1)
    at AsyncSeriesHook.lazyCompileHook (D:\demo\raxmini\raxmini\node_modules\tapable\lib\Hook.js:154:20)
    at Compiler.emitAssets (D:\demo\raxmini\raxmini\node_modules\webpack\lib\Compiler.js:491:19)
    at onCompiled (D:\demo\raxmini\raxmini\node_modules\webpack\lib\Watching.js:51:19)
    at D:\demo\raxmini\raxmini\node_modules\webpack\lib\Compiler.js:681:15
    at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\demo\raxmini\raxmini\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook (D:\demo\raxmini\raxmini\node_modules\tapable\lib\Hook.js:154:20)
    at D:\demo\raxmini\raxmini\node_modules\webpack\lib\Compiler.js:678:31
    at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\demo\raxmini\raxmini\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:20:1)
    at AsyncSeriesHook.lazyCompileHook (D:\demo\raxmini\raxmini\node_modules\tapable\lib\Hook.js:154:20)
    at D:\demo\raxmini\raxmini\node_modules\webpack\lib\Compilation.js:1423:35
    at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\demo\raxmini\raxmini\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:9:1)
    at AsyncSeriesHook.lazyCompileHook (D:\demo\raxmini\raxmini\node_modules\tapable\lib\Hook.js:154:20)
    at D:\demo\raxmini\raxmini\node_modules\webpack\lib\Compilation.js:1414:32
    at eval (eval at create (D:\demo\raxmini\raxmini\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:16:1)
    at D:\demo\raxmini\raxmini\node_modules\rax-miniapp-runtime-webpack-plugin\src\index.js:58:11
    at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\demo\raxmini\raxmini\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:12:1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! raxmini@0.1.0 start: `rax-app start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the raxmini@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\dell\AppData\Roaming\npm-cache\_logs\2021-01-20T06_11_06_333Z-debug.log
The terminal process "C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -Command npm run start" terminated with exit code: 1.

Terminal will be reused by tasks, press any key to close it.
`

**Comment by evinLiang** [comment]
> 可以在 github 创建一个示例项目

demo地址：[https://github.com/evinLiang/raxdemo](https://github.com/evinLiang/raxdemo)

**Comment by evinLiang** [comment]
> 可以在 github 创建一个示例项目

demo地址：[https://github.com/evinLiang/raxdemo](https://github.com/evinLiang/raxdemo)

**Comment by ChrisCindy** [comment]
@basilbai windows 的问题已经修复，重新安装一下依赖看下

**Comment by ChrisCindy** [comment]
@evinLiang 同上
