### ISSUE TITLE
[Question]如何正确使用@unocss/webpack

### ISSUE THREAD

**Issue by xmsz** [alibaba/rax#2321]
背景
- https://github.com/unocss/unocss/blob/main/packages/webpack/README.md
```
{
  "targets": ["web"],
  "webpack5": true,
  "webpackPlugins": {
    "@unocss/webpack": {}
  }
}

```
报错
```
ERR! CONFIG Failed to load webpack config.
ERR! Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.
 - configuration[0].plugins[8] misses the property 'apply'. Should be:
   function
   -> The run point of the plugin, required method.
ValidationError: Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.
 - configuration[0].plugins[8] misses the property 'apply'. Should be:
   function
   -> The run point of the plugin, required method.
    at validate (.pnpm/@builder+pack@0.5.2/node_modules/@builder/pack/deps/schema-utils3/index.js:1:153657)
    at validateSchema (.pnpm/@builder+pack@0.5.2/node_modules/@builder/pack/deps/webpack/bundle5.js:151268:2)
    at create (.pnpm/@builder+pack@0.5.2/node_modules/@builder/pack/deps/webpack/bundle5.js:154748:24)
    at webpack (.pnpm/@builder+pack@0.5.2/node_modules/@builder/pack/deps/webpack/bundle5.js:154795:32)
    at f (.pnpm/@builder+pack@0.5.2/node_modules/@builder/pack/deps/webpack/bundle5.js:109940:16)
    at .pnpm/build-scripts@1.2.1/node_modules/build-scripts/lib/service/start.js:56:24
    at Generator.next (<anonymous>)
    at fulfilled (.pnpm/build-scripts@1.2.1/node_modules/build-scripts/lib/service/start.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  errors: [
    {
      keyword: 'anyOf',
      dataPath: '[0].plugins[8]',
      schemaPath: '#/items/anyOf',
      params: {},
      message: 'should match some schema in anyOf',
      schema: [Array],
      parentSchema: [Object],
      data: [Object],
      children: [Array]
    }
  ],
  schema: {
    definitions: {
      Amd: [Object],
      AssetFilterItemTypes: [Object],
      AssetFilterTypes: [Object],
      AssetGeneratorDataUrl: [Object],
      AssetGeneratorDataUrlFunction: [Object],
      AssetGeneratorDataUrlOptions: [Object],
      AssetGeneratorOptions: [Object],
      AssetInlineGeneratorOptions: [Object],
      AssetModuleFilename: [Object],
      AssetParserDataUrlFunction: [Object],
      AssetParserDataUrlOptions: [Object],
      AssetParserOptions: [Object],
      AssetResourceGeneratorOptions: [Object],
      AuxiliaryComment: [Object],
      Bail: [Object],
      CacheOptions: [Object],
      CacheOptionsNormalized: [Object],
      Charset: [Object],
      ChunkFilename: [Object],
      ChunkFormat: [Object],
      ChunkLoadTimeout: [Object],
      ChunkLoading: [Object],
      ChunkLoadingGlobal: [Object],
      ChunkLoadingType: [Object],
      Clean: [Object],
      CleanOptions: [Object],
      CompareBeforeEmit: [Object],
      Context: [Object],
      CrossOriginLoading: [Object],
      Dependencies: [Object],
      DevServer: [Object],
      DevTool: [Object],
      DevtoolFallbackModuleFilenameTemplate: [Object],
      DevtoolModuleFilenameTemplate: [Object],
      DevtoolNamespace: [Object],
      EmptyGeneratorOptions: [Object],
      EmptyParserOptions: [Object],
      EnabledChunkLoadingTypes: [Object],
      EnabledLibraryTypes: [Object],
      EnabledWasmLoadingTypes: [Object],
      Entry: [Object],
      EntryDescription: [Object],
      EntryDescriptionNormalized: [Object],
      EntryDynamic: [Object],
      EntryDynamicNormalized: [Object],
      EntryFilename: [Object],
      EntryItem: [Object],
      EntryNormalized: [Object],
      EntryObject: [Object],
      EntryRuntime: [Object],
      EntryStatic: [Object],
      EntryStaticNormalized: [Object],
      EntryUnnamed: [Object],
      Environment: [Object],
      Experiments: [Object],
      ExperimentsCommon: [Object],
      ExperimentsNormalized: [Object],
      ExternalItem: [Object],
      ExternalItemFunctionData: [Object],
      ExternalItemValue: [Object],
      Externals: [Object],
      ExternalsPresets: [Object],
      ExternalsType: [Object],
      FileCacheOptions: [Object],
      Filename: [Object],
      FilenameTemplate: [Object],
      FilterItemTypes: [Object],
      FilterTypes: [Object],
      GeneratorOptionsByModuleType: [Object],
      GlobalObject: [Object],
      HashDigest: [Object],
      HashDigestLength: [Object],
      HashFunction: [Object],
      HashSalt: [Object],
      HotUpdateChunkFilename: [Object],
      HotUpdateGlobal: [Object],
      HotUpdateMainFilename: [Object],
      HttpUriAllowedUris: [Object],
      HttpUriOptions: [Object],
      HttpUriOptionsAllowedUris: [Object],
      IgnoreWarnings: [Object],
      IgnoreWarningsNormalized: [Object],
      Iife: [Object],
      ImportFunctionName: [Object],
      ImportMetaName: [Object],
      InfrastructureLogging: [Object],
      JavascriptParserOptions: [Object],
      Layer: [Object],
      LazyCompilationDefaultBackendOptions: [Object],
      LazyCompilationOptions: [Object],
      Library: [Object],
      LibraryCustomUmdCommentObject: [Object],
      LibraryCustomUmdObject: [Object],
      LibraryExport: [Object],
      LibraryName: [Object],
      LibraryOptions: [Object],
      LibraryType: [Object],
      Loader: [Object],
      MemoryCacheOptions: [Object],
      Mode: [Object],
      ModuleFilterItemTypes: [Object],
      ModuleFilterTypes: [Object],
      ModuleOptions: [Object],
      ModuleOptionsNormalized: [Object],
      Name: [Object],
      NoParse: [Object],
      Node: [Object],
      NodeOptions: [Object],
      Optimization: [Object],
      OptimizationRuntimeChunk: [Object],
      OptimizationRuntimeChunkNormalized: [Object],
      OptimizationSplitChunksCacheGroup: [Object],
      OptimizationSplitChunksGetCacheGroups: [Object],
      OptimizationSplitChunksOptions: [Object],
      OptimizationSplitChunksSizes: [Object],
      Output: [Object],
      OutputModule: [Object],
      OutputNormalized: [Object],
      Parallelism: [Object],
      ParserOptionsByModuleType: [Object],
      Path: [Object],
      Pathinfo: [Object],
      Performance: [Object],
      PerformanceOptions: [Object],
      Plugins: [Object],
      Profile: [Object],
      PublicPath: [Object],
      RawPublicPath: [Object],
      RecordsInputPath: [Object],
      RecordsOutputPath: [Object],
      RecordsPath: [Object],
      Resolve: [Object],
      ResolveAlias: [Object],
      ResolveLoader: [Object],
      ResolveOptions: [Object],
      ResolvePluginInstance: [Object],
      RuleSetCondition: [Object],
      RuleSetConditionAbsolute: [Object],
      RuleSetConditionOrConditions: [Object],
      RuleSetConditionOrConditionsAbsolute: [Object],
      RuleSetConditions: [Object],
      RuleSetConditionsAbsolute: [Object],
      RuleSetLoader: [Object],
      RuleSetLoaderOptions: [Object],
      RuleSetLogicalConditions: [Object],
      RuleSetLogicalConditionsAbsolute: [Object],
      RuleSetRule: [Object],
      RuleSetRules: [Object],
      RuleSetUse: [Object],
      RuleSetUseItem: [Object],
      ScriptType: [Object],
      SnapshotOptions: [Object],
      SourceMapFilename: [Object],
      SourcePrefix: [Object],
      StatsOptions: [Object],
      StatsValue: [Object],
      StrictModuleErrorHandling: [Object],
      StrictModuleExceptionHandling: [Object],
      Target: [Object],
      TrustedTypes: [Object],
      UmdNamedDefine: [Object],
      UniqueName: [Object],
      WarningFilterItemTypes: [Object],
      WarningFilterTypes: [Object],
      WasmLoading: [Object],
      WasmLoadingType: [Object],
      Watch: [Object],
      WatchOptions: [Object],
      WebassemblyModuleFilename: [Object],
      WebpackOptionsNormalized: [Object],
      WebpackPluginFunction: [Object],
      WebpackPluginInstance: [Object]
    },
    title: 'WebpackOptions',
    description: 'Options object as provided by the user.',
    type: 'object',
    additionalProperties: false,
    properties: {
      amd: [Object],
      bail: [Object],
      cache: [Object],
      context: [Object],
      dependencies: [Object],
      devServer: [Object],
      devtool: [Object],
      entry: [Object],
      experiments: [Object],
      externals: [Object],
      externalsPresets: [Object],
      externalsType: [Object],
      ignoreWarnings: [Object],
      infrastructureLogging: [Object],
      loader: [Object],
      mode: [Object],
      module: [Object],
      name: [Object],
      node: [Object],
      optimization: [Object],
      output: [Object],
      parallelism: [Object],
      performance: [Object],
      plugins: [Object],
      profile: [Object],
      recordsInputPath: [Object],
      recordsOutputPath: [Object],
      recordsPath: [Object],
      resolve: [Object],
      resolveLoader: [Object],
      snapshot: [Object],
      stats: [Object],
      target: [Object],
      watch: [Object],
      watchOptions: [Object]
    }
  },
  headerName: 'Webpack',
  baseDataPath: 'configuration',
  postFormatter: [Function: postFormatter]
}
```

**Comment by wjq990112** [comment]
这个可能需要自定义 build.plugin.js 才能做了，因为 UnoCSS 的 Webpack Plugin 导出的方式比较特殊，是 default 导出的

**Comment by wjq990112** [comment]
我给你一个示例，可以试一下：
```js
// build.plugin.js
const UnoCSS = require('@unocss/webpack').default;

module.exports = ({ onGetWebpackConfig }) => {
  onGetWebpackConfig((config) => {
    config
    .plugin('UnoCSSPlugin')
    .use(UnoCSS)
    .end()
  });
};
```

```json
// build.json
{
  "plugins": ["./build.plugin.js"]
}
```

**Comment by wjq990112** [comment]
可以试一下，然后现在 Rax 也能比较轻松地使用 Tailwind CSS 和 WindiCSS，欢迎体验！

**Comment by xmsz** [comment]
> 可以试一下，然后现在 Rax 也能比较轻松地使用 Tailwind CSS 和 WindiCSS，欢迎体验！

牛逼

**Comment by xmsz** [comment]
```
const UnoCSS = require('@unocss/webpack').default;
const presetUno = require('@unocss/preset-uno').default;

module.exports = ({ onGetWebpackConfig }) => {
  onGetWebpackConfig((config) => {
    config
      .plugin('UnoCSSPlugin')
      .use(UnoCSS({ presets: [presetUno()] }))
      .end();
  });
};

```

但是使用的时候
```
<View className="ma4"></View>
```

没有效果 构建出来也没有 我不知道我漏了哪步

**Comment by wjq990112** [comment]
示例可能有点问题，我没有尝试，具体用法可以看下 Webpack Chain 是怎么配置 Webpack Plugin 的，按照 Webpack Chain 的方式修改 config 就可以

**Comment by wjq990112** [comment]
我看了你的代码，我理解是传参数的方式不正确，Webpack Chain 给 Webpack Plugin 传参数的时候不能直接传入 UnoCSS 里，而是要作为第二个参数，像这样：

```ts
const UnoCSS = require('@unocss/webpack').default;
const presetUno = require('@unocss/preset-uno').default;

module.exports = ({ onGetWebpackConfig }) => {
  onGetWebpackConfig((config) => {
    config
      .plugin('UnoCSSPlugin')
      .use(UnoCSS, [{ presets: [presetUno()] }])
      .end();
  });
};
```

**Comment by xmsz** [comment]
情况一：我用简易webpack项目会实时更新（不过简易项目和普通vite项目都是直接注入在页面style中所以看不到_virtual_uno.css是否有变化） 不确定是不是其他配置影响

```

const MiniCssExtractPlugin = require('mini-css-extract-plugin');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const UnoCSS = require('@unocss/webpack').default;
const { presetUno } = require('@unocss/preset-uno');

module.exports = (env, { mode = 'production' }) => {
  const isDev = mode === 'development';

  return {
    mode,
    module: {
      rules: [
        {
          test: /\.js$/,
          exclude: /(node_modules)/,
          use: [
            {
              loader: 'babel-loader',
              options: {
                presets: ['@babel/preset-react'],
              },
            },
          ],
        },
        {
          test: /\.css$/,
          use: [
            isDev ? 'style-loader' : MiniCssExtractPlugin.loader,
            'css-loader',
          ],
        },
      ],
    },
    plugins: [
      new UnoCSS({
        include: [/\.js$/],
        exclude: [/node_modules/],
        presets: [presetUno()],
      }),
      !isDev && new MiniCssExtractPlugin(),
      new HtmlWebpackPlugin({
        template: './src/index.html',
      }),
    ].filter(Boolean),
  };
};

```

有点麻烦

**Comment by xmsz** [comment]
问题三：https://github.com/unocss/unocss/issues/386 确实不会先经过postcss 很蛋疼

**Comment by xmsz** [comment]
问题一：https://windicss.org/integrations/webpack.html 我尝试windicss也是没有实时更新 需要重新编译 

然后如果用webpack插件 windicss会经过postcss 还是挺好的
如果用postcss插件则 windcss则还是需要考虑顺序问题

但都是需要重新编译才会生成

**Comment by xmsz** [comment]
问题一：https://windicss.org/integrations/webpack.html 我尝试windicss也是没有实时更新 需要重新编译 

然后如果用webpack插件 windicss会经过postcss 还是挺好的
如果用postcss插件则 windcss则还是需要考虑顺序问题

但都是需要重新编译才会生成

**Comment by wjq990112** [comment]
可能使用 Webpack Plugin 扫描样式并生成的这个逻辑在 rpx 的体系下都存在一点问题，试下用 WindiCSS 的 PostCSS 模式，或者 Tailwind CSS，因为 Tailwind CSS 本质是一个 postcss 插件

**Comment by wjq990112** [comment]
如果需要在关闭 Webpack 缓存，可以试下带上 `--force` 参数启动，关闭 Webpack 的缓存之后看下是否还存在无法实时更新的问题？

**Comment by xmsz** [comment]
> 可能使用 Webpack Plugin 扫描样式并生成的这个逻辑在 rpx 的体系下都存在一点问题，试下用 WindiCSS 的 PostCSS 模式，或者 Tailwind CSS，因为 Tailwind CSS 本质是一个 postcss 插件。

我用windCSS的postCSS模式，rpx没有转换，估计是顺序问题

**Comment by wjq990112** [comment]
我看下 WindiCSS 的 PostCSS 插件是怎么实现的，这个问题应该跟插件实现有关系。

**Comment by xmsz** [comment]
> --force

```
rax-app start --force
```

我是这样写 + postcss插件 还是没有效果

**Comment by wjq990112** [comment]
理论上来说确实跟 PostCSS 插件的顺序有关系，稍等我验证一下给你一个解决方案。

**Comment by wjq990112** [comment]
```js
// build.plugin.js
const WindiCSS = require('postcss-windicss');

const checkPostcssLoader = (config, ruleName) =>
  config.module.rules.has(ruleName) && config.module.rule(ruleName).uses.has('postcss-loader');

module.exports = ({ onGetWebpackConfig }) => {
  onGetWebpackConfig((config) => {
    const rules = ['css', 'css-module', 'css-global'];

    rules.forEach((rule) => {
      if (checkPostcssLoader(config, rule)) {
        config.module
          .rule(rule)
          .use('postcss-loader')
          .tap((options) => ({
            ...options,
            postcssOptions: {
              ...options.postcssOptions,
              plugins: [WindiCSS, ...options.postcssOptions.plugins],
            },
          }));
      }
    });
  });
};
```

**Comment by xmsz** [comment]
> ```js
> // build.plugin.js
> const WindiCSS = require('postcss-windicss');
> 
> const checkPostcssLoader = (config, ruleName) =>
>   config.module.rules.has(ruleName) && config.module.rule(ruleName).uses.has('postcss-loader');
> 
> module.exports = ({ onGetWebpackConfig }) => {
>   onGetWebpackConfig((config) => {
>     const rules = ['css', 'css-module', 'css-global'];
> 
>     rules.forEach((rule) => {
>       if (checkPostcssLoader(config, rule)) {
>         config.module
>           .rule(rule)
>           .use('postcss-loader')
>           .tap((options) => ({
>             ...options,
>             postcssOptions: {
>               ...options.postcssOptions,
>               plugins: [WindiCSS, ...options.postcssOptions.plugins],
>             },
>           }));
>       }
>     });
>   });
> };
> ```

我用新项目 提示"PostCSS plugin postcss-windicss requires PostCSS 8."

旧项目顺序还是不对（可能是没更新，正常应该和新项目一样的提示）

**Comment by wjq990112** [comment]
PostCSS 8 的问题有点难受，建议还是用 Tailwind CSS 吧，有 PostCSS 7 的 compat。

**Comment by xmsz** [comment]
> PostCSS 8 的问题有点难受，建议还是用 Tailwind CSS 吧，有 PostCSS 7 的 compat。

Tailwind还需要额外插件把px转成rpx
