### ISSUE TITLE
templates下的模板编译失败

### ISSUE THREAD

**Issue by weixinjie** [alibaba/rax#799]
例如:我编译template_zhihu这个模板
执行 
> npm install 
后再直接 
> npm run start 报错

template-zhihu@0.6.4 start /Users/weixinjie/Ali_Custom_Developer/rax/templates/template-zhihu
webpack-dev-server --host 0.0.0.0 --no-info

module.js:550
    throw err;
    ^

Error: Cannot find module 'webpack/bin/config-yargs'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/weixinjie/Ali_Custom_Developer/rax/templates/template-zhihu/node_modules/webpack-dev-server/bin/webpack-dev-server.js:54:1)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! template-zhihu@0.6.4 start: `webpack-dev-server --host 0.0.0.0 --no-info`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the template-zhihu@0.6.4 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/weixinjie/.npm/_logs/2018-12-14T09_05_45_846Z-debug.log

**Comment by yuanyan** [comment]
templates 问题正在修复，随我们后会迁移到 github.com/raxjs group 下

**Comment by yuanyan** [comment]
可以看已经迁移的模版：https://github.com/raxjs/template-buy
